# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 55f054cbf237e5fee993429f62ce69da78b95a2c442cd7a9d3fa80d52dd23fcc8493168558960c851d4b5d69576eee615859086771e6a738ac7cbe17a0b807f9

test:
  secret_key_base: 419f5f421675bbf7c43cd3ac81b701c56ee7d33e4159a3c75c7d4db8dcfbe14b9afdefa589bc045ba87883453204e472474ddbb385d0c7903663668f9e1b5b21

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
